version: '3.8'

services:
  lavalink:
    container_name: lavalink
    image: ghcr.io/lavalink-devs/lavalink:4.1.1
    restart: unless-stopped
    environment:
      - _JAVA_OPTIONS=-Xmx2G
      - SERVER_PORT=2333
      - SERVER_ADDRESS=0.0.0.0
    volumes:
      # Mount your application.yml from /opt/lavalink
      - /opt/lavalink/application.yml:/opt/Lavalink/application.yml:ro
      # Persist logs directory
      - /opt/lavalink/logs:/opt/Lavalink/logs
    network_mode: host
    healthcheck:
      test: 'curl -H "Authorization: youshallnotpass" -s http://localhost:2333/version'
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
